GET http://localhost:8080/movies
####
GET http://localhost:8080/movies/1
####
POST http://localhost:8080/movies
Content-Type: application/json

{
    "id": "4",
    "title": "fantastico#",
    "release_date": "2020-06-02 13:00:00",
    "synopsis": "um filme fantastico",
    "usr_rating": "10"
}

#####
PUT http://localhost:8080/movies/1
Content-Type: application/json

{
  "id": "3",
  "title": "fantastica fabrica de chocolate",
  "release_date": "2020-06-03 14:05:22",
  "synopsis": "um filme fantastico",
  "usr_rating": "10"
}

####
GET http://localhost:8080/movies/letter_metrics_top10
